name: NoDebugging (master)

on:
  push:
    tags:
      - H[1-2]_v[0-9]+.[0-9]+.[0-9]+

jobs:
  NoDebugging_master:

    name: NoDebugging Job (master)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Запуск скрипта для проверки флага отладки
      run: bash .github/scripts/NoDebugging.sh
