name: NoObjects (feature)

on:
  push:
    tags:
      - H[1-2]_v[0-9]+.[0-9]+.[0-9]+_feature_*

jobs:
  NoObjects_feature:

    name: NoObjects Job (feature)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Запуск скрипта для проверки директории объектных файлов
      run: bash .github/scripts/NoObjects.sh
